#### Array Operations

In [2]:
import numpy as np

In [3]:
x = np.array([45,33,12,67,54,27,41,20])

In [4]:
x

array([45, 33, 12, 67, 54, 27, 41, 20])

In [5]:
print(x)

[45 33 12 67 54 27 41 20]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.dtype

dtype('int64')

In [8]:
x.size

8

In [9]:
x = np.array([45,33,12,67,54,27,41,20], dtype=np.int16)

In [10]:
x

array([45, 33, 12, 67, 54, 27, 41, 20], dtype=int16)

In [11]:
x.dtype

dtype('int16')

In [12]:
y = np.array([4.5,3.3,1.2,6.7,5.4,2.7,4.1,2.0])

In [13]:
y

array([4.5, 3.3, 1.2, 6.7, 5.4, 2.7, 4.1, 2. ])

In [14]:
y.dtype

dtype('float64')

In [15]:
x + 10

array([55, 43, 22, 77, 64, 37, 51, 30], dtype=int16)

In [16]:
x / 2

array([22.5, 16.5,  6. , 33.5, 27. , 13.5, 20.5, 10. ])

In [17]:
z = np.arange(1,11)

In [18]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
M = np.array([[1,2,3],[4,5,6]])

In [21]:
M

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
M.shape

(2, 3)

In [23]:
M.size

6

In [24]:
M.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [25]:
M.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Series

In [27]:
import pandas as pd

In [28]:
s = pd.Series([45,22,16,49,75,62])

In [29]:
s

0    45
1    22
2    16
3    49
4    75
5    62
dtype: int64

In [30]:
s.size

6

In [31]:
s.shape

(6,)

In [32]:
s1 = pd.Series([45,22,16,49,75,62], index=range(100,106))

In [33]:
s1

100    45
101    22
102    16
103    49
104    75
105    62
dtype: int64

#### Data Frame

In [35]:
a = pd.Series([1,2,3,4,5])
b = pd.Series(['Vijay','Vikas','Vina','Vivek','Vijeta'])
c = pd.Series([56.77, 82.34, 76.44, 65.33, 69.23])

In [37]:
df = pd.DataFrame({
    'roll': a,
    'name': b,
    'marks': c
})

In [38]:
df

roll    name  marks
0     1   Vijay  56.77
1     2   Vikas  82.34
2     3    Vina  76.44
3     4   Vivek  65.33
4     5  Vijeta  69.23

In [39]:
type(df)

pandas.core.frame.DataFrame

In [40]:
df.shape

(5, 3)

In [41]:
df.dtypes

roll       int64
name      object
marks    float64
dtype: object